# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fiestagram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fiestagram
    pod 'Parse'
    pod 'SAConfettiView', :git => 'https://github.com/gokhanakkurt/SAConfettiView', :branch => 'swift3'
end
